### ISSUE TITLE
Dropped leading zeroes causes error

### ISSUE THREAD

**Issue by wilmington** [xraystyle/mac_format#1]
On an OSX device with input of `8:0:37:d7:a:45` I get 

`"8037d7a45" appears to be an invalid MAC address!`

**Comment by xraystyle** [comment]
Hmm, interesting. Is this a format that's commonly used by any particular vendor? Currently the app checks that the mac, when stripped of punctuation, is 12 characters long and only contains valid hex characters, i.e. 0-9, a-f. 

If this is a common enough use-case it could probably be done without too much refactoring.

**Comment by wilmington** [comment]
I've [so far] only seen this  format used by OSX e.g. 

```
% arp -an | grep  192.168.10.245
? (192.168.10.245) at 8:0:37:d7:a:45 on en0 ifscope [ethernet]

```

Solaris does it as well apparently

**Comment by xraystyle** [comment]
Wacky, it only does it on OS X with the arp command that I can see. `ifconfig | grep ether` returns standard linux format MAC addresses...

Alright, something to look into. I suppose it wouldn't be terribly difficult to add the leading zeroes back in before stripping the punctuation and validating the MAC address.

**Comment by wilmington** [comment]
I'd not noticed the `ifconfig | grep ether` behaviour.  I've no access to a Solaris box to see what it does.

Certainly not a major issue
